/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  EventEmitter,
} from '@stencil/core';
import {
  IInputEvent,
} from './input/input.interface';


export namespace Components {

  interface KvControlList {
    /**
    * star count
    */
    'count': number;
    /**
    * rating
    */
    'rating': number;
    /**
    * star size
    */
    'size': number;
  }
  interface KvControlListAttributes extends StencilHTMLAttributes {
    /**
    * star count
    */
    'count'?: number;
    /**
    * rating
    */
    'rating'?: number;
    /**
    * star size
    */
    'size'?: number;
  }

  interface KvInput {
    /**
    * name of input field
    */
    'name': string;
    /**
    * type of input field
    */
    'type': string;
    'value': string | number;
  }
  interface KvInputAttributes extends StencilHTMLAttributes {
    /**
    * name of input field
    */
    'name'?: string;
    /**
    * change input event
    */
    'onInputChange'?: (event: CustomEvent<IInputEvent>) => void;
    /**
    * type of input field
    */
    'type'?: string;
    'value'?: string | number;
  }

  interface KvRating {
    /**
    * star count
    */
    'count': number;
    /**
    * rating
    */
    'rating': number;
    /**
    * star size
    */
    'size': number;
  }
  interface KvRatingAttributes extends StencilHTMLAttributes {
    /**
    * star count
    */
    'count'?: number;
    /**
    * rating
    */
    'rating'?: number;
    /**
    * star size
    */
    'size'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'KvControlList': Components.KvControlList;
    'KvInput': Components.KvInput;
    'KvRating': Components.KvRating;
  }

  interface StencilIntrinsicElements {
    'kv-control-list': Components.KvControlListAttributes;
    'kv-input': Components.KvInputAttributes;
    'kv-rating': Components.KvRatingAttributes;
  }


  interface HTMLKvControlListElement extends Components.KvControlList, HTMLStencilElement {}
  var HTMLKvControlListElement: {
    prototype: HTMLKvControlListElement;
    new (): HTMLKvControlListElement;
  };

  interface HTMLKvInputElement extends Components.KvInput, HTMLStencilElement {}
  var HTMLKvInputElement: {
    prototype: HTMLKvInputElement;
    new (): HTMLKvInputElement;
  };

  interface HTMLKvRatingElement extends Components.KvRating, HTMLStencilElement {}
  var HTMLKvRatingElement: {
    prototype: HTMLKvRatingElement;
    new (): HTMLKvRatingElement;
  };

  interface HTMLElementTagNameMap {
    'kv-control-list': HTMLKvControlListElement
    'kv-input': HTMLKvInputElement
    'kv-rating': HTMLKvRatingElement
  }

  interface ElementTagNameMap {
    'kv-control-list': HTMLKvControlListElement;
    'kv-input': HTMLKvInputElement;
    'kv-rating': HTMLKvRatingElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
